# 減肥平衡遊戲 - 標準配置文件
# 此文件定義遊戲中所有可用的行動及其效果

# 行動列表
actions:
  - name: "運動"
    description: "去健身房運動1小時"
    effects:
      weight: -0.5      # 體重變化 (kg)
      health: 8         # 健康變化 (0-100)
      happiness: -3     # 快樂變化 (0-100)
    energy_cost: 15     # 體力消耗 (可選，預設10)
    
  - name: "慢跑"
    description: "在公園慢跑30分鐘"
    effects:
      weight: -0.3
      health: 5
      happiness: 2
      social: 1
    energy_cost: 10
    
  - name: "讀書"
    description: "閱讀一本好書"
    effects:
      knowledge: 6
      happiness: 3
      social: -2
    energy_cost: 5
    
  - name: "工作"
    description: "努力工作賺錢"
    effects:
      wealth: 8
      health: -4
      happiness: -2
      weight: 0.2
    energy_cost: 12
    
  - name: "聚會"
    description: "和朋友聚會聊天"
    effects:
      social: 8
      happiness: 5
      wealth: -3
      weight: 0.3
    energy_cost: 8
    
  - name: "休息"
    description: "在家放鬆休息"
    effects:
      happiness: 6
      health: 3
      knowledge: -1
    energy_cost: 0
    
  - name: "烹飪"
    description: "自己做健康料理"
    effects:
      health: 4
      happiness: 3
      wealth: -2
      weight: -0.2
    energy_cost: 6
    
  - name: "冥想"
    description: "進行正念冥想"
    effects:
      happiness: 7
      health: 2
      knowledge: 2
    energy_cost: 3
    
  - name: "購物"
    description: "去商場購物"
    effects:
      happiness: 4
      wealth: -5
      social: 2
      weight: 0.1
    energy_cost: 7
    
  - name: "學習"
    description: "參加線上課程"
    effects:
      knowledge: 8
      wealth: -1
      happiness: 1
    energy_cost: 8

# 遊戲設定
game_settings:
  # 角色初始數值
  initial_stats:
    weight: 80.0
    health: 50
    happiness: 50
    wealth: 50
    knowledge: 50
    social: 50
  
  # 遊戲目標
  target_weight: 65.0
  max_days: 100
  
  # 失敗條件閾值
  failure_thresholds:
    health: 10
    happiness: 10
  
  # 統計數值限制
  stat_limits:
    weight_min: 40.0
    weight_max: 150.0
    stat_min: 0
    stat_max: 100

# 隨機事件系統
random_events:
  # 事件觸發機率 (0.0-1.0)
  probability: 0.3
  
  # 隨機事件列表
  events:
    - name: "下雨天憂鬱"
      description: "下雨了，心情有點憂鬱"
      effects:
        happiness: -2
      weight: 10          # 事件權重，數字越大越容易發生
      
    - name: "朋友鼓勵"
      description: "收到朋友的鼓勵訊息！"
      effects:
        happiness: 3
        social: 2
      weight: 15
      
    - name: "意外收穫"
      description: "路上撿到零錢"
      effects:
        wealth: 2
        happiness: 1
      weight: 5
      
    - name: "勵志內容"
      description: "看到勵志影片"
      effects:
        happiness: 2
        knowledge: 1
      weight: 12
      
    - name: "輕微感冒"
      description: "感冒了一點"
      effects:
        health: -3
      weight: 8
      
    - name: "優質睡眠"
      description: "睡得很好"
      effects:
        health: 3
        happiness: 2
      weight: 15
      
    - name: "交通堵塞"
      description: "遇到嚴重塞車，心情煩躁"
      effects:
        happiness: -3
      weight: 12
      
    - name: "美食誘惑"
      description: "看到美味甜點，忍不住吃了一些"
      effects:
        weight: 0.2
        happiness: 3
      weight: 10
      
    - name: "工作順利"
      description: "工作上有了突破性進展"
      effects:
        happiness: 4
        wealth: 3
        knowledge: 2
      weight: 8
      
    - name: "舊友重逢"
      description: "偶遇多年未見的老朋友"
      effects:
        happiness: 5
        social: 4
      weight: 6
      
    - name: "網路購物"
      description: "忍不住在網路上買了一些東西"
      effects:
        wealth: -4
        happiness: 2
      weight: 9
      
    - name: "健康檢查"
      description: "定期健康檢查，一切正常"
      effects:
        health: 2
        happiness: 3
      weight: 7

# 條件事件系統（基於當前狀態觸發）
conditional_events:
  # 低健康狀態事件
  - condition:
      stat: "health"
      operator: "<"
      value: 20
    event:
      name: "疲倦狀態"
      description: "因為健康狀況不佳，今天感到很疲倦..."
      effects:
        happiness: -5
    probability: 0.8
    
  # 低快樂狀態事件
  - condition:
      stat: "happiness"
      operator: "<"
      value: 20
    event:
      name: "情緒低落"
      description: "心情很低落，做什麼都提不起勁..."
      effects:
        health: -3
    probability: 0.7
    
  # 低財富狀態事件
  - condition:
      stat: "wealth"
      operator: "<"
      value: 20
    event:
      name: "經濟壓力"
      description: "錢包空空如也，有點擔心生活費..."
      effects:
        happiness: -3
    probability: 0.6
    
  # 高社交狀態事件
  - condition:
      stat: "social"
      operator: ">"
      value: 80
    event:
      name: "朋友關懷"
      description: "朋友們都很關心你的近況，感覺很溫暖！"
      effects:
        happiness: 3
    probability: 0.5
    
  # 高知識狀態事件
  - condition:
      stat: "knowledge"
      operator: ">"
      value: 80
    event:
      name: "知識應用"
      description: "學到了很多新知識，工作表現更好了！"
      effects:
        wealth: 5
    probability: 0.4
    
  # 體重接近目標時的鼓勵事件
  - condition:
      stat: "weight"
      operator: "<="
      value: 70
    event:
      name: "減重進展"
      description: "朋友們都注意到你的減重成果，紛紛稱讚！"
      effects:
        happiness: 4
        social: 2
    probability: 0.3
    
  # 極度疲勞狀態
  - condition:
      stat: "health"
      operator: "<"
      value: 15
    event:
      name: "需要休息"
      description: "身體發出警訊，強烈需要休息..."
      effects:
        happiness: -3
        knowledge: -2
    probability: 0.9